<?php

date_default_timezone_set('America/Chicago');
$feature_event = array(

	array(
		"title" 	=> "Cincinnati Music Festival",
		"location"	=> "Cincinnati, OH",
		"date" 		=> "July 25-27, 2024",
		"end"		=> strtotime("July 27, 2024"),
		"img" 		=> "images/slides/splash-mmf.jpg",
		"link" 		=> "/nati-music-festival",
		"desc"		=>"Book now for an all-inclusive Cincinnati Music Festival travel package to experience renowned performers and Grown and Sophisticated Mid-Day Cruise."
	),
	array(
		"title" 	=> "Grown & Sophisticated Mid-Day Cruise",
		"location"=> "Cincinnati, OH",
		"date" 		=> "July 27, 2024",
		"end"		=> strtotime("July 27, 2024"),
		"img" 		=> "images/slides/splash-gsc.jpg",
		"link" 		=> "/nati-music-festival",
		"desc"		=> "Book now for an all-inclusive Cincinnati Music Festival travel package to experience renowned performers and Grown and Sophisticated Mid-Day Cruise.",
	),
	array(
		"title" 	=> "Essence Festival",
		"location"	=> "New Orleans, LA",
		"date" 		=> "July 5 -7, 2024",
		"end"		=> strtotime("July 7, 2024"),
		"img" 		=> "images/featured-events/featured-event-efw.jpg",
		"link" 		=> "/essence-festival",
		"desc"		=>"Book now for an all-inclusive Essence Festival travel package to experience renowned performers and celebrities.",
	),
	array(
		"title" 	=> "Daytopia",
		"location"	=> "Montgomery, AL",
		"date" 		=> "April 13, 2024",
		"end"		=> strtotime("April 13, 2024"),
		"img" 		=> "images/featured-events/featured-event-daytopia.jpg",
		"link" 		=> "/daytopia",
		"desc"		=>"Come enjoy a day party events at Bama Lanes. DJ and Live Music, Food, Bowling, and lots of fun!",
	),
	array(
		"title" 	=> "Magic City Classic",
		"location"	=> "Birmingham, AL",
		"date" 		=> "October 26-28, 2022",
		"end"		=> strtotime("October 28, 2023"),
		"img" 		=> "images/featured-events/featured-event-mcc.jpg",
		"link" 		=> "/classic",
		"desc"		=>"",
	),
	array(
		"title" 	=> "NBA All-Star Weekend",
		"location"	=> "Indianapolis, Indiana",
		"date" 		=> "February 16, 2024",
		"end"		=> strtotime("February 18, 2024"),
		"img" 		=> "images/slides/splash-nba.jpg",
		"link" 		=> "/nba-allstar",
		"desc"		=>"Lets turn up at the All-Star Game with YOLLO's exclusive package, featuring A-list parties, and all-inclusive perks!",
	),
	array(
		"title" 	=> "Party Gras Cruise",
		"location"	=> "Montgomery, AL",
		"date" 		=> "August 12-14, 2024",
		"end"		=> strtotime("August 14, 2024"),
		"img" 		=> "images/featured-events/featured-event-pg.jpg",
		"link" 		=> "/partygras",
		"desc"		=> "Party Gras: Bottles and Beads is a weekend event featuring good music, adult beverages, mingling, and fun for all attendees.",
	),
	array(
		"title" 	=> "Urban Fiesta Weekend",
		"location"	=> "San Juan, Puerto Rico",
		"date" 		=> "May 24-27, 2024",
		"end"		=> strtotime("May 27, 2024"),
		"img" 		=> "images/slides/splash-urban-fiesta-puerto-rico.jpg",
		"link" 		=> "/urban-fiesta-puerto-rico",
		"desc"		=> "Explore Puerto Rico with YOLLO Group Services! Book your Urban Fiesta adventure now for a memorable Caribbean experience.",
	),
	array(
		"title" 	=> "Urban Ski Weekend",
		"location"	=> "Gatlinburg, Tennessee",
		"date" 		=> "February 2-5, 2024",
		"end"		=> strtotime("February 5, 2024"),
		"img" 		=> "images/slides/splash-urban-ski.jpg",
		"link" 		=> "/urban-ski-weekend",
		"desc"		=> "Join YOLLO for an unforgettable Urban Ski Weekend in Gatlinburg, Tennessee, with tailored skiing experiences for all skill levels."
	),
	array(
		"title" 	=> "Day Getaway Cruise",
		"location"	=> "",
		"date" 		=> "May 5, 2018",
		"end"		=> strtotime("May 5, 2018"),
		"img" 		=> "images/featured-events/featured-event-dgc.jpg",
		"link" 		=> "/day-getaway-cruise",
		"desc"		=>"",
    ),
    array(
		"title" 	=> "Spring Fling Music Fest",
		"location"	=> "",
		"date" 		=> "May 30, 2020",
		"end"		=> strtotime("May 30, 2020"),
		"img" 		=> "images/featured-events/featured-event-springfling.jpg",
		"link" 		=> "/spring-fling-festival",
		"desc"		=>"",
	),
	array(
		"title" 	=> "HBCU Alumni Getaway Cruise",
		"location"	=> "Cabo San Lucas + Ensenada",
		"date" 		=> "December 2-7, 2024",
		"end"		=> strtotime("December 7, 2024"),
		"img" 		=> "images/slides/splash-alumni.jpg",
		"link" 		=> "/alumni-getaway-cruise",
		"desc"		=> "Calling all HBCU alums, join YOLLO on an amazing cruise to Cabo San Lucas and Ensenada, Mexico! Envision sandy beaches, turquoise waters, and the lively local culture.",
    ),
	array(
		"title" 	=> "London To Paris",
		"location"	=> "Paris, France",
		"date" 		=> "December 31 - Jan 5, 2023",
		"end"		=> strtotime("January 5, 2023"),
		"img" 		=> "images/featured-events/featured-event-london.jpg",
		"link" 		=> "/london-to-paris",
		"desc"		=>"",
    ),
	array(
		"title" 	=> "Dubai Takeover",
		"location"	=> "Dubai",
		"date" 		=> "August 31 - Sept 5, 2023",
		"end"		=> strtotime("September 5, 2023"),
		"img" 		=> "images/featured-events/featured-event-dubai.jpg",
		"link" 		=> "/dubai-takeover",
		"desc"		=>"",
    ),
	array(
		"title" 	=> "Egypt Takeover",
		"location"	=> "Egypt",
		"date" 		=> "November 1-6, 2023",
		"end"		=> strtotime("November 1, 2023"),
		"img" 		=> "images/featured-events/featured-event-egypt.jpg",
		"link" 		=> "/egypt-takeover",
		"desc"		=>"",
    ),
	array(
		"title" 	=> "Greece Takeover",
		"location"	=> "Greece",
		"date" 		=> "October 5-11, 2023",
		"end"		=> strtotime("October 11, 2023"),
		"img" 		=> "images/featured-events/featured-event-greece.jpg",
		"link" 		=> "/greece-takeover",
		"desc"		=>"",
    ),
	array(
		"title" 	=> "Italy Takeover",
		"location"	=> "Italy",
		"date" 		=> "October 31-November 5, 2023",
		"end"		=> strtotime("November 5, 2023"),
		"img" 		=> "images/featured-events/featured-event-italy.jpg",
		"link" 		=> "/italy-takeover",
		"desc"		=>"",
    ),
	array(
		"title" 	=> "Fade To May",
		"location"	=> "Memphis, TN",
		"date" 		=> "May 5-7, 2023",
		"end"		=> strtotime("May 1, 2023"),
		"img" 		=> "images/featured-events/featured-event-may.jpg",
		"link" 		=> "/fade-to-may",
		"desc"		=>"",
    ),
    array(
		"title" 	=> "CIAA Tourney Weekend",
		"location"	=> "Baltimore, MD",
		"date" 		=> "March 1-3, 2024",
		"end"		=> strtotime("March 3, 2024"),
		"img" 		=> "images/slides/splash-tourney.jpg",
		"link" 		=> "/ciaa",
		"desc"		=> "The CIAA tournament held in Baltimore is one of the most attended events among HBCUs in the nation.",
    ),
    array(
		"title" 	=> "Shamrock Sea Escape",
		"location"	=> "Cozumel, Mexico",
		"date" 		=> "March 17-22, 2025",
		"end"		=> strtotime("March 17, 2025"),
		"img" 		=> "images/slides/splash-shamrock.jpg",
		"link" 		=> "/shamrock-sea-escape",
		"desc"		=> "Experience St. Patrick's Day with YOLLO's all-inclusive cruise. Immerse yourself in a day filled with camaraderie, relaxation, and top-notch entertainment.",
    )/*,
    array(
		"title" 	=> "Spring Breakaway",
		"date" 		=> "March 25-29, 2021",
		"end"		=> strtotime("March 29, 2021"),
		"img" 		=> "images/featured-events/featured-event-sba.jpg",
		"link" 		=> "/spring-breakaway-cruise"
	),
	array(
		"title" 	=> "Get on the Bus",
		"location"	=> "",
		"date" 		=> "August 27-29, 2020",
		"end"		=> strtotime("August 29, 2020"),
		"img" 		=> "images/featured-events/featured-event-gob.jpg",
		"link" 		=> "/get-on-the-bus",
		"desc"		=>"",
    ),
	array(
		"title" 	=> "Da Kickback",
		"location"	=> "Montgomery, AL",
		"date" 		=> "September 29, 2023",
		"end"		=> strtotime("September 29, 2023"),
		"img" 		=> "images/featured-events/featured-event-kickback.jpg",
		"link" 		=> "/da-kickback",
		"desc"		=>"",
	),
	array(
		"title" 	=> "Groove Cruise",
		"location"	=> "",
		"date" 		=> "July 21, 2018",
		"end"		=> strtotime("July 21, 2018"),
		"img" 		=> "images/featured-events/featured-event-groove-cruise.jpg",
		"link" 		=> "/groove-cruise",
		"desc"		=>"",
	),
	array(
		"title" 	=> "Urban Fantasy Cruise",
		"location"	=> "",
		"date" 		=> "September 4-5, 2020",
		"end"		=> strtotime("September 05, 2020"),
		"img" 		=> "images/featured-events/featured-event-ufc.jpg",
		"link" 		=> "/urban-fantasy",
		"desc"		=>"",
	),
    array(
		"title" 	=> "Black Beach Weekend Cruise",
		"date" 		=> "August 28, 2021",
		"end"		=> strtotime("August 28, 2021"),
		"img" 		=> "images/featured-events/featured-event-bbw.jpg",
		"link" 		=> "/black-beach"
	)*/

);

usort(
	$feature_event,function($a,$b){

		return $a['end']-$b['end'];

	}
);
?>